### ISSUE TITLE
Insert Image widget

### ISSUE THREAD

**Issue by kkotwal94** [liferay/alloy-editor#270] opened 2015-06-30 14:35 UTC
With the same example or test files i presented before, the insert image widget doesnt do anything or atleast won't appear, everything else works fine however. Secondly, how do I use both bootstrap and the alloy css file simultaneously? They conflict, so I don't know if I should edit one or the other. Was looking for advice towards it.

https://www.dropbox.com/s/4s32xqadz3769mf/test2.zip?dl=0

remove the css file of bootstrap to see the widget issue.

**Comment by jbalsas** [comment] 2015-06-30 15:25
Hey @kkotwal94 

Which image widget do you refer to? If it's the add buttons which work on the demo, but not on the project, the reason is the same as in #263. It will be fixed as soon as we release 0.3.6 (most surely today). You should update your version of AlloyEditor to get the fixes once it's done.

About the css issue. They should not collapse at all. We are using bootstrap3 in alloyeditor.com and are not seeing any issues. The editor also looks good in your demo with or without the bootstrap css. Can you post a screenshot of what you mean?

Thanks!

**Comment by kkotwal94** [comment] 2015-06-30 16:58
The css issue is fixed, the issue still remains with the image widget however.

Demo:

https://www.dropbox.com/s/4s32xqadz3769mf/test2.zip?dl=0

It is version 0.3.6 btw.

**Comment by ipeychev** [comment] 2015-06-30 20:47
Thanks for the report and sorry for the issue! I was able to reproduce in Firefox. Will fix that in a few hours.

**Closed** 2015-07-01 10:27 UTC
Labels: bug

**Comment by ipeychev** [comment] 2015-07-01 10:42
Fixed and released v0.3.7.

Thanks for the report!

**Comment by kkotwal94** [comment] 2015-07-01 12:08
No problem!
