### ISSUE TITLE
Headline formatting from Word produces unwanted entities when pasted into Alloy

### ISSUE THREAD

**Issue by konradoboza** [liferay/alloy-editor#1177] opened 2019-03-11 09:15 UTC
Hi,

I observed an issue with heading formatting in Word desktop:
1. Type "Test 1234".
2. Mark the text as itemized/numbered list.
3. Change paragraph to Heading1-3.
4. Copy text and paste it into Alloy.

**Result:**
After pasting it into Alloy editor you will be presented with:
`sdrt. 1234`

I reproduced the issue on a live demo.
Alloy Editor: v1.5.19
Browser: Chrome 72.0.3626.121, Safari 12.0.3, Firefox 65.0.1
OS: macOS High Sierra 10.13.6.

**Comment by julien** [comment] 2019-03-19 12:11
Hi @konradoboza,

Thanks for reporting this issue.

Although this issues seems more related to Word than to alloy-editor, I have some questions:
 
- Does copying and pasting the same text in a text editor produce the same output?

- Does this issue also happen with the latest 1.5.22 or v2.0.0-beta.2 releases? 
  (We updated CKEDITOR along the way, which might change this behaviour)

On my side, I can't test with Word right now, but I did try to reproduce the issue with LibreOffice Writer with no luck.

**Comment by konradoboza** [comment] 2019-03-20 08:26
Hi @julien,

thank you for the response.

It might be Word-formatting related issue, as I didn't find any reliable way to reproduce - it is only happening on a specific document. I tried to reverse-engineer the formatting attached but wasn't able to find the exact steps.

1. Copy& paste produced the same output.
2. It is happening also on the newest version 1.5.22.

If this would be of help I can provide you with the exact document.

Best,
Konrad

**Comment by julien** [comment] 2019-03-20 14:37
Hi @konradoboza,

Thanks for the reply.

Since copy & paste is producing the same output in a text editor and this is only happening with one document, I'm going to close this issue for now.

**Closed by julien** 2019-03-20 14:37 UTC
