### ISSUE TITLE
Edge - Image disappears when drag and drop

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/alloy-editor#1164] opened 2019-02-27 21:37 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Dragging the image in Edge causes it to disappear.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

0. Using Edge
1. Visit demo https://alloyeditor.com/
2. Attempt to drag and drop image position.

**What is the expected behavior?**
The image does not disappear.  It either (1) Drags and Drops at the cursor location or (2) CKEditor Drag and Drop behavior where it drops image at cursor height location.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**

Edge.  Can't test demo with IE11 but also likely reproducible with IE11.

As far as I can tell it's always been broken on Edge since https://github.com/liferay/alloy-editor/issues/839.  (And prior to that issue drag and drop did not work)

**Comment by SpencerWoo** [comment] 2019-02-27 23:21
Currently investigating.  Will edit this comment shortly

**Comment by julien** [comment] 2019-04-24 14:36
Closing this since it doesn't seem to be reproducible 

![dnd_edge](https://user-images.githubusercontent.com/5572/56667991-12122600-66af-11e9-8588-fad8e267cee6.gif)

**Closed by julien** 2019-04-24 14:36 UTC
Labels: browser: edge
