### ISSUE TITLE
Buttons do not work properly when an attribute is added.

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#535] opened 2016-06-06 08:19 UTC
When  "id" or any attribute is added to an element (strong,italic,underline), it doesn't work properly i.e. 
When a style (e.g Bold) is applied using strong (as implemented in Alloy editor). In this case once selection is set to bold and an "id" attribute is appended in the strong tag. Due to this user cannot set selection back to normal style, instead when bold button is clicked another strong tag is added and this behavior continues if button is clicked multiple times.
However using "span" element (by defining in ck-editor config.js ) resolves this issue but then the state of buttons cannot be preserved.(as reported [here](https://github.com/liferay/alloy-editor/issues/533)).

Same is the case with Underline and Italic.

**Comment by ipeychev** [comment] 2016-06-07 06:29
Hey @qasid,

I think this issue should be reported to CKEditor. This is not something we control. It might be misconfiguration too. Why don't you open an issue following the instructions [here](http://dev.ckeditor.com/wiki/Bugs) and then post the link to it, so we would be able to track the progress?

Thanks,

**Comment by jbalsas** [comment] 2016-06-08 06:31
This is probably the same behaviour we had to fix for AlloyEditor to work with YUI3. See https://github.com/liferay/alloy-editor/issues/399 for more information.

**Comment by ipeychev** [comment] 2016-06-08 07:04
Yeah, it is, but I agree this issue is odd and it is probably a bug in either CKEditor or the browser itself. It might be also not a bug, but expected behavior for some reason and it won't hurt to know it.

Thanks,

**Comment by qasid** [comment] 2016-06-09 09:51
Hello @ipeychev & @jbalsas ,  
I have reported the issue to CKEditor (see [#14681](https://dev.ckeditor.com/ticket/14681#ticket)).

**Comment by ipeychev** [comment] 2016-06-09 14:24
You see - CKEditor guys say this is not a bug. We will close this issue too.

**Closed by ipeychev** 2016-06-09 14:24 UTC
Labels: help wanted, question
