### ISSUE TITLE
Crash on React 16.2.0

### ISSUE THREAD

**Issue by josemontiel** [liferay/alloy-editor#808] opened 2018-01-08 23:12 UTC
AlloyEditor: 1.5.1
React: 16.2.0

<img width="1029" alt="screen shot 2018-01-08 at 12 24 03 pm" src="https://user-images.githubusercontent.com/7999856/34697046-42181dc4-f49f-11e7-8492-406e8b43dfe7.png">

**Comment by Minivera** [comment] 2018-01-25 22:09
I can confirm the issue.

I have temporarily fixed the issue by importing `import AlloyEditor from 'alloyeditor/dist/alloy-editor/alloy-editor-all.js';` instead of the base package.

I think that adding an import for the independent `prop-types` package inside the react specific files or alloy editor may fix the issue.

**Comment by jbalsas** [comment] 2018-02-19 16:55
Hey @Minivera, @josemontiel, sorry for the late response. As it was pointed out, `AlloyEditor@1.5.1` just tried to find a way to be compatible with `React-16` without introducing backwards incompatible changes.

Indeed, to make it work, the developer needs to add the `prop-types` package either in the build process or as a global script.

We're working on a `2.0` version that should remove this dependency by directly upgrading to React16: https://github.com/liferay/alloy-editor/tree/feature/alloyeditor_2.0

**Comment by Minivera** [comment] 2018-02-23 19:55
This is a very specific use case, but we are using Meteor and the build process is a little unique.

Meteor dynamically import files and make sure that all imports are only used by those that actually needs them, so adding prop-types as a global script is not really possible in this case.

For now, we had to go with a custom draftJs implementation, we'll wait for 2.0. I also need to implement the editor in an iframe which may also cause issues (it does for DraftJs, hence the custom implementation).

**Comment by nomadus** [comment] 2018-04-01 15:58
Hi @jbalsas, I am having the same issue with React 16.3.0. Adding prop-types globally did not solve the issue, what would be my options to have it working? I am using CRA.

**Comment by nomadus** [comment] 2018-04-04 16:43
Any feedback on how to workaround the issue?

**Comment by dsuarezv** [comment] 2018-04-05 09:35
Hey @jbalsas, tried your suggestion with the changes in https://github.com/liferay/alloy-editor/tree/feature/alloyeditor_2.0, but got the same error with prop-types. I'm wondering if there are any specific instructions to make this branch work?

I see it has a big refactor going on, however it seems that the default bundle used (dist/alloyeditor/alloy-editor-no-react.js) still suffers the problem. 

Maybe you can provide some pointers to try the 2.0 branch?

Thanks!

**Comment by jbalsas** [comment] 2018-04-05 10:16
Hey everyone, sorry for all this trouble. We are a bit understaff at the moment and it has been rather impossible to follow thrugh :(

The `2.0` branch is still in a very unstable state, so I wouldn't go that route just yet.

@matuzalemsteles, can you take a look at this to see what are we missing to use latest `React` in the current AlloyEditor version?

**Comment by matuzalemsteles** [comment] 2018-04-05 14:26
Hey guys, I'm working on the changes to `2.0` and I also do not recommend going with this branch so far, I'm stabilizing some things, we're probably going to have `prop-types` for AlloyEditor.

With the recent launch of React and change of the life cycles that will come the front. We'll start working on it later in 2.0, as well as the removal of `reactCreateClass`. So far I'm using the `create-react-class` package to go with 2.0 faster.

Hey @Minivera, we will be happy if you work on this later, so far I would recommend waiting for the 2.0 release.

**Comment by jbalsas** [comment] 2018-04-05 15:15
Hey @vbence86, do you remember how did we setup this to work with the existing version? I can't seem to find the docs where we explained how to do this... 🤷‍♂️

**Comment by matuzalemsteles** [comment] 2018-04-06 02:55
Hey guys, I was investigating a bit of the crash problem with React `16.x.x`, with the latest version. I've developed a small workaround so you can move on.

https://github.com/matuzalemsteles/alloyeditor-react

AlloyEditor had already [implemented a solution](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/vendor/react-bridge.js) so it did not have a breaking change in the latest version.

Just for clarification, once we add `prop-types` and` create-react-class` in our React 16.xx application, there may still be errors that `prop-types` and` create-react- class` was not found or does not exist. It is ideal that you load those packages before loading the AlloyEditor. This is because currently the AlloyEditor runs as soon as it is loaded.

Hey @jbalsas correct me if I'm wrong please 🙂.

**Comment by vbence86** [comment] 2018-04-06 06:05
@jbalsas I'm afraid I don't quite remember what was the exact twist, but it was rather hacky nevertheless. It might be better just draw the line and communicate the breaking changes for backward compatibility otherwise there will be a technical dept slowly creeping around that logic.

**Comment by Minivera** [comment] 2018-04-06 13:33
Not sure it this is it, but when I was looking through the code in january, I noticed that it was made backwards compatible thanks to these lines in the `alloy-editor-core.js` file.

https://github.com/liferay/alloy-editor/blob/15caaf0fc32cad680c54b59f215e56ac277c644c/dist/alloy-editor/alloy-editor-core.js#L290

```
    var React = (function() {
    	return (0, eval)('this').React;
    }());

    if (typeof React === 'undefined') {
        React = AlloyEditor.React;
    }

    var ReactDOM = (function() {
        return (0, eval)('this').ReactDOM;
    }());

    if (typeof React === 'undefined') {
        ReactDOM = AlloyEditor.ReactDOM;
    }

     /**
  * React bridge between v16 and older version
  */
var PropTypes = (function() {
    return (0, eval)('this').PropTypes || React.PropTypes;
}());

var createReactClass = (function() {
    return (0, eval)('this').createReactClass || React.createClass;
}());  
```

It seems that @matuzalemsteles solutions works because that code is executed as soon as the module is loaded and it sees `window.PropTypes ` (In this case, `this.PropTypes `) as set where in our case, it doesn't.

**Comment by matuzalemsteles** [comment] 2018-04-06 13:51
Hey @Minivera, In that case it would be the [react-bridge](https://github.com/liferay/alloy-editor/blob/master/src/ui/react/vendor/react-bridge.js) to get the compatibility between the older and the newer version, which I put in the link just above.

But let me know your use case, I do not know if I understand what you mean.

**Comment by Minivera** [comment] 2018-04-06 14:46
I'll do some tests this evening to see if your solution could be working for my use case.

Simply told, we are using meteor which transforms imports through a dynamic system that makes sure we only import what's actually needed. This caused an issue where I could not force the `prop-type` package to the window object for Alloy Editor as Meteor mostly did whatever it wanted with my imports.

Looking at [your specific solution](https://github.com/matuzalemsteles/alloyeditor-react/blob/master/src/registerServiceWorker.js) it looks like we were going in the same direction, though I did not use await at the time. My last post was mostly trying to figure out why your solution worked and mine did not, I think the await made sure that react-bridge had access to the updated window object when it loads.

I will also need to make sur this does not break our SSR implementation, but it shouldn't be a problem.

**Comment by matuzalemsteles** [comment] 2018-04-06 15:13
Thanks for the details @Minivera, now I'm more aware.

That's pretty bad right now, AlloyEditor it uses a lot:
```javascript
(function() {
    //...
}());
```

And this is the problem, even when you import `prop-types` and` create-react-class` and add to `window` or` React`, AlloyEditor has already been executed well before and ends up accusing the error of not find `PropTypes`. With the use of `async await` I guarantee that` PropTypes` and `createReactClass` will be loaded and ready before loading the AlloyEditor. With the use of SSR I'm not sure if this would work, maybe yes it has to be tested. Let me know what your results will be.

We are removing this in much of the AlloyEditor codebase in 2.0, as well as `prop-types`. We will be adding `create-react-class` in the core for now.

**Comment by dsuarezv** [comment] 2018-04-09 12:56
Thanks @matuzalemsteles, your sample helped a lot!

**Comment by Minivera** [comment] 2018-04-09 15:41
@matuzalemsteles I can confirm your example works fine on meteor 16.1.1 and React 16.2 with SSR enabled.

SSR does not cause any issues since the lifecycle methods are not called when rendering on the server, thus using `window` without any `isClient` check will not cause any errors. Though I would suggest still adding those checks in case React changes how lifecycle works on the server.

Here is my code : 

index.html
```html
<head>
    <link href="/alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">
    <script type="text/javascript">
        window.ALLOYEDITOR_BASEPATH = 'alloy-editor/';
        window.CKEDITOR_BASEPATH = 'alloy-editor/';
    </script>
</head>
<body>
    <div id="app"></div>
</body>
```

App.js
```jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';

import createReactClass from 'create-react-class';

const loadAlloy = async () => {
    await PropTypes;
    await createReactClass;

    window.PropTypes = PropTypes;
    window.createReactClass = createReactClass;

    const AlloyEditor = require('alloyeditor');

    return AlloyEditor;
};

class App extends Component {
	constructor(props) {
		super(props);
	}
	
	componentDidMount() {
		const { alloyEditorConfig } = this.props;

		loadAlloy().then((alloyeditor) => {
				this._editor = alloyeditor.editable('container', alloyEditorConfig);
		}).catch((e) => {
			console.log(e);
		});
	}

	componentWillUnmount() {
		this._editor.destroy();
	}

    render() {
	return (
		<div id="container">
			<h1>
				AlloyEditor will make this content editable
			</h1>
			<p>
				To install React, follow the instructions on <a href="https://github.com/facebook/react/">GitHub</a>.
			</p>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel metus nunc. Maecenas rhoncus congue faucibus. Sed finibus ultrices turpis. Mauris nulla ante, aliquam a euismod ut, scelerisque nec sem. Nam dapibus ac nulla non ullamcorper. Sed vestibulum a velit non lobortis. Proin sit amet imperdiet urna. Aenean interdum urna augue, vel mollis tortor dictum vitae. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris vitae suscipit magna.
			</p>
		</div>
	);
    }
}
```

All the alloy-editor files are in the public directory for meteor.

**Comment by matuzalemsteles** [comment] 2018-04-09 15:55
Thanks for the @dsuarezv and @Minivera return.

Hey @Minivera, Awesome, thanks for sharing the details in SSR running. I will take care of improving the example and describing about the SSR and we will also add the official documentation so that others can do the same.

Thanks guys!

**Comment by wincent** [comment] 2019-02-08 01:30
The 2.x-develop branch is now upgraded (v16.7.0 at the time I write this, although I'll submit a PR to bump to v16.8.0) so I'm going to close this.

**Closed by wincent** 2019-02-08 01:30 UTC
Labels: question
