### ISSUE TITLE
Formatting cannot be removed after text is deselected

### ISSUE THREAD

**Issue by sei-dmorda** [liferay/alloy-editor#399] opened 2015-12-15 14:26 UTC
Hi folks,

I'm using Alloy Editor 0.7.0 with Liferay 6.2 EE. For the most part, it works great and we love it. However, I've run into an odd issue with removing formatting that seems to affect all browsers I've tested including Google Chrome, Firefox, and IE 11.

**Steps to reproduce**
1. Select editable text
2. Click the "Bold" button
3. Unselect the text
4. Select the text again
5. Click the "Bold" button

**Expected Results**
The bold formatting is removed from the highlighted text.

**Actual Results**
The bold formatting is not removed. You have to click the "Remove Format" button to remove the bold formatting.

However, if you do the following it works as expected.
1. Select editable text
2. Click the "Bold" button to bold the text
3. Click the "Bold" button to unbold the text

So it only seems to occur after the text has been unselected.

I fired up Chrome Dev Tools and inspected what was going on. It seems as though Liferay is adding an ID to the tags when they are selected. For example, if I bold some text, unselect it, and then select it again once the formatting is added...an ID is added and the tag looks like this.

`<strong id="yui_patched_v3_11_0_1_1450130-016004_1523">my text</strong>`

Once that ID is added, I can't click the "Bold" button to unbold it. Instead, I have to click the "Remove Format" button to remove all formatting on that text. This seems to affect bold, italics, underline, etc.

If there's anything else I can do to help troubleshoot, let me know.

**Comment by sei-dmorda** [comment] 2015-12-15 15:01
This may be related to the following issue:

https://github.com/yui/yui3/issues/1925

**Comment by jbalsas** [comment] 2015-12-15 15:13
Hi @sei-dmorda awesome to hear you got AlloyEditor working in 6.2!! :astonished: 

I've actually been able to reproduce in the `master` branch, so I'll investigate ASAP.

**Comment by ipeychev** [comment] 2015-12-15 16:42
As hint, to you, Chema, I believe @sei-dmorda nailed it - the reason should be exactly the id and YUI should be patched.

**Comment by jbalsas** [comment] 2015-12-15 17:19
Hey Iliyan, didn't we patch this already somewhere?

**Comment by jbalsas** [comment] 2015-12-15 17:21
Like [here](https://github.com/liferay/alloy-editor/blob/a9188ba979b2faebc6eda8428c72ddf564d3b51c/src/ui/yui/src/plugins/selector-patch.js)? :joy:

**Comment by ipeychev** [comment] 2015-12-15 17:26
Maybe this is not used?

**Comment by sei-dmorda** [comment] 2015-12-15 18:08
Awesome, glad you all were able to reproduce the issue. For what it's worth, I temporarily patched selector-native.js with ipeychev's patch in Liferay and that resolved the issue. 

https://github.com/ipeychev/yui3/commit/05e03c51cdbddd25a039536edc3456763c798a2c

I've attached the differences between the Liferay 6.2 one and the patched one. I would definitely prefer if there were a way to fix this in alloy-editor though so we don't have to do a one-off in Liferay.

[fixed-selector-native.txt](https://github.com/liferay/alloy-editor/files/63019/fixed-selector-native.txt)

**Comment by ipeychev** [comment] 2015-12-15 18:47
I don't believe this is a bug in AlloyEditor, sorry. It is it charge of the content inside the editable area and it is not anyone's business to touch the elements there.
What I fixed in this patch, was a bug in YUI, which is used in Liferay. When YUI disappears from Liferay, the bug will disappear by itself. Until then, this patch is needed.

**Comment by jbalsas** [comment] 2015-12-15 19:02
Hey @sei-dmorda, I agree with @ipeychev, this is not AlloyEditor's fault. I'll see that we patch Liferay's YUI fork so it ends up in the product and fixes the issue. I'll file a bug in Liferay's JIRA tomorrow to make sure we fix this.

Thanks a lot for noticing!!

**Comment by sei-dmorda** [comment] 2015-12-15 20:41
Awesome, thank you!

**Closed** 2015-12-19 05:17 UTC
Labels: invalid

**Comment by sei-dmorda** [comment] 2016-01-04 16:41
Hi jbalsas,

Just wondered if you had a chance to file a bug with Liferay. If it's a public bug in their issue tracking system, I'd like to put myself on the watchers list for it.

Thanks!

**Comment by jbalsas** [comment] 2016-01-04 16:48
Hey @sei-dmorda,

I filed two issues, one for our YUI fork and one for portal:
- https://issues.liferay.com/browse/AUI-2063
- https://issues.liferay.com/browse/LPS-61676

We need to merge the fix in our yui fork and then bring it to Portal. I'll try to push to get this in before the end of the week.

Thanks!

**Comment by sei-dmorda** [comment] 2016-01-04 21:23
That's fantastic news. Once those changes are in place, how would they show up in a release. Would they be part of a Liferay 6.2 EE Service Pack, or would we need to manually roll them in?

**Comment by jbalsas** [comment] 2016-01-04 22:38
Hey @sei-dmorda, sorry, but I wouldn't really know if these changes are going to make it in a 6.2EE Service Pack. I really don't know what's been backported so far. I guess the best approach would be to contact support and indicate that you could use this fix to see if it can be safely backported.

In any case, you could add the fix to the hook that adds AlloyEditor to your Portal (I assume that's what you have) so it would still be somewhat contained.

**Comment by felix3508** [comment] 2016-01-12 05:24
Hey @sei-dmorda , sorry to bother you. I also want to use Alloy Editor with Liferay 6.2 EE. But I don't know how to configure it. I try to modify ckeditor properties  value to alloyeditor, but it doesn't work. If convenience, could you please give me some steps to help me configure it? Thanks a lot!
