### ISSUE TITLE
Alloy Editor crashes on React 16

### ISSUE THREAD

**Issue by emilecantin** [liferay/alloy-editor#770] opened 2017-09-27 18:00 UTC
React.PropTypes and React.createClass have been deprecated since React 15.5, released [April 2017](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html). Alloy still uses them, which crashes on React 16.

Here is the crash:
```
Uncaught (in promise) TypeError: Cannot read property 'string' of undefined
    at alloy-editor-no-react.js:8526
    at alloy-editor-no-react.js:8557
    at Object.<anonymous> (alloy-editor-no-react.js:16541)
    at Object.Array.concat.module.exports.root (alloy-editor-no-react.js:16541)
    at __webpack_require__ ...
```

This references [this line](https://github.com/liferay/alloy-editor/blob/cf534baf33229283ce8a3457972d4efeb8e79dc0/src/ui/react/src/components/base/button-command.js#L19), which uses React.PropTypes.string.

**Comment by jbalsas** [comment] 2017-09-28 11:37
Hey @emilecantin, thanks for letting us know!

We were planning to switch to [`Metal.js`](https://metaljs.com/) as part of our [`2.0` milestone](https://github.com/liferay/alloy-editor/issues/771), so we wouldn't have a dependency with React.

Would that change the way you're using AlloyEditor? Can you add some more context on how you're consuming it? That way we can properly plan for it.

**Comment by emilecantin** [comment] 2017-09-28 13:52
We're a React app, so we're simply `import`ing AlloyEditor in our app, and using it as the documentation states. I believe a switch to another library would probably change the way we use it.

Honestly, we'd prefer keeping everything React-based, so we'd probably end up switching if the bundle size goes up significantly.

**Comment by jbalsas** [comment] 2017-09-28 16:13
Thanks for the answer, @emilecantin, that certainly will help us shape the roadmap in the upcoming months...

Did you pick AlloyEditor just for that reason? Is there something you'd like to see in the future?

**Comment by emilecantin** [comment] 2017-09-28 18:14
Mostly, we wanted a rich text editor that would play well with React, and we liked the "tooltip" UI (that appears on highlight).

**Comment by JiriZidek** [comment] 2017-10-02 11:46
For us AlloyEditor (as a CKE editor wrapper) has value only as React component. Switching to anything else is like telling "we switch from Java to .NET": showstopper. Then we would consider forking current status and maintaining pace with React or completely leaving Alloy because of incompatibility.

**Comment by MiniCodeMonkey** [comment] 2017-10-02 20:22
Would it make sense to just to get rid of the PropTypes definitions for now? It doesn't look like it's very easy to add the new `prop-types` dependency in this project.

**Comment by jbalsas** [comment] 2017-10-03 06:50
Thanks a lot for the feedback, @emilecantin, @JiriZidek, @MiniCodeMonkey (and almost anonymous reaction commenters 😉)!

This is very valuable for us to plan for the future. AlloyEditor was conceived from the beginning to allow for different UIs, so we can simply provide another one and keep the React one for React consumption.

@vbence86, could you take a look at what else might be needed to support React16 while you're looking at replacing the mixins and old usage of `.createClass`?

@JiriZidek, @MiniCodeMonkey, is there any feature you might be missing or you'd like to have? All feedback/suggestions are welcome! :)

**Comment by JiriZidek** [comment] 2017-10-03 06:53
Regarding PropTypes - we consume AlloyEditor form TypeScript and we use homemade .d.ts file - so no benefit of PropTypes for us at all.

**Comment by JiriZidek** [comment] 2017-10-03 06:57
There is one difficult feature we miss: Paste from Word. We never made it work perfectly. But I guess it's more CKE feature.

**Comment by vbence86** [comment] 2017-10-03 08:21
I'll keep all these remarks in mind while updating the implementation.

**Comment by jbalsas** [comment] 2017-10-03 09:08
Hey @JiriZidek, yeah, `Paste from Word` is a CKEditor plugin that should be working out of the box, but it is definitely hard to get right. We could try to work together on those, but the fastest way to fix them would be to open issues directly in the [CKEditor GitHub repo](https://github.com/ckeditor/ckeditor-dev/issues).

Regarding your `TypeScript` usage and custom `.d.ts`, we'd be very interested in knowing more about it. Is there something (code, examples, tutorial drafts) that you'd be interested in sharing with us? We could add examples in the [Use section](https://alloyeditor.com/docs/use/) of the [AlloyEditor site](https://alloyeditor.com/). We might even be able to adopt and maintain the `.d.ts` declaration file as part of a larger Dev.Experience story... what do you think?

**Comment by JiriZidek** [comment] 2017-10-03 09:51
Feel free to use attached files as example editor component to be used in TSX. React 15.x d.ts files come from DefinitelyTyped and I included them just for completeness (otherwise it won't compile in TypeScript 2.0-2.5).

[AlloyEditor.zip](https://github.com/liferay/alloy-editor/files/1351819/AlloyEditor.zip)

**Comment by lserwatka** [comment] 2017-10-10 11:31
Hey @jbalsas 

We are using AlloyEditor at eZ (https://github.com/ezsystems), mainly in eZ Platform CMS. We recently switched from legacy YUI JS framework to React 16, and I have to admit that switching you Metal.js will force use to reconsider other options for online editor. All our UI components are React based, as invested quite some time to rewrite them from legacy code. Have you made your final decision yet about React vs. Metal.js for 2.x?

**Comment by jbalsas** [comment] 2017-10-10 11:37
Hey @lserwatka, based on the feedback on this thread, we will likely maintain the React layer and just create another one based on Metal.js. AlloyEditor was designed to allow for different UIs from the beginning for this purpose, so that is our current thinking at the moment.

**Comment by lserwatka** [comment] 2017-10-10 11:59
Hey @jbalsas 

Thank you for your quick answer. This is really good news for us. I believe it is wise to continue supporting React. Last question from my side. Do you have any ETA for AlloyEditor release supporting React 16?

**Comment by JiriZidek** [comment] 2017-10-10 12:41
We'd approciate continuation of React support. Anyway I guess that popularity of React is not going to decline within a year or two and for us our application is expected to stay on it for several years.

**Comment by jbalsas** [comment] 2017-10-11 07:21
Hey @lserwatka, @JiriZidek, @vbence86 started looking into it last week. He already ran some codemods and saw what manual changes might be needed.

Based on the changes we might be forced to release an early `2.0.0` if it breaks for older versions, to make sure we don't break people's apps inadvertently... What do you think about this, @ipeychev?

I think we should be able to release a `React 16` compatible version in 2 weeks 🤞 , but we'll keep you updated.

**Comment by lserwatka** [comment] 2017-10-11 07:28
Hey @jbalsas 

This is really great timeline. Thank you for letting us know and being open on listening feedback from your users. Keep your great work!

**Comment by ipeychev** [comment] 2017-10-11 09:56
> @jbalsas
> Based on the changes we might be forced to release an early 2.0.0 if it breaks for older versions, to make sure we don't break people's apps inadvertently... What do you think about this, @ipeychev?


I would say releasing 2.0.0 is fine in this case 👍

**Comment by MiniCodeMonkey** [comment] 2017-10-25 15:06
For those eager to upgrade, I created a simple (temporary) fork that has React 16 support: https://github.com/Footage-Firm/alloy-editor

Just make sure to pull in the `create-react-class` compatibility package in your project.

**Comment by vbence86** [comment] 2017-10-25 15:46
@MiniCodeMonkey Thanks for your time and effort you've put it. FYI, we've also implemented a version v1.5.0 that works with React. I've cast my eyes over your changes and just to follow them up I'd wanted to point out that you've removed all the PropTypes from your implementation that is definitely an undesired change.

**Comment by MiniCodeMonkey** [comment] 2017-10-25 16:12
@vbence86 Yep, it was certainly just a temporary change because we needed to get our React 16 update out the door, and this was the only roadblock. I opt'ed to remove them, because I didn't see a good way to pull in third party dependencies with the current build system.

Great to hear that v1.5.0 now supports React 16 - really appreciate the super fast turnaround time!

**Comment by vbence86** [comment] 2017-10-25 17:44
@MiniCodeMonkey It's a pleasure, The version containing the fix is about to get released so hold tight and will notify you once it's out.

**Comment by lserwatka** [comment] 2017-11-02 20:07
@vbence86 how close are you to release a new version that is supporting React 16?

**Comment by jbalsas** [comment] 2017-11-02 20:10
Hey @lserwatka, we're investigating https://github.com/liferay/alloy-editor/issues/768 which should be the last fix for the `1.5.0` milestone.

We're looking to release sometime before the end of next week.

PS: Closing here since this was actually merged to `master`!

**Closed by jbalsas** 2017-11-02 20:10 UTC
Labels: bug, enhancement

**Comment by lserwatka** [comment] 2017-11-02 20:34
Hey @jbalsas, this is great! Thank you for quick response.

**Comment by sunpietro** [comment] 2017-12-18 09:46
Hey, looks like the AlloyEditor doesn't work with React 16.2.0
It crashes on `PropTypes` and other stuff. Please, see the screenshot:
![zrzut ekranu 2017-12-18 o 10 45 10](https://user-images.githubusercontent.com/1736658/34099724-9a14094a-e3e0-11e7-84cb-c630fee9c280.jpg)

The sample code to reproduce issues:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>React16</title>
    <style>
        html {
            font-size: 16px;
        }
        body {
            margin: 0;
            padding: 1rem;
            font-size: 1rem;
            font-family: Arial, sans-serif;
            line-height: 1.44;
        }
    </style>
</head>
<body>
    <h1>React16 + Alloy</h1>
    <div id="alloy-editor"></div>
    <link rel="stylesheet" type="text/css" href="node_modules/alloyeditor/dist/alloy-editor/assets/alloy-editor-ocean-min.css">
    <script src="node_modules/react/umd/react.development.js"></script>
    <script src="node_modules/react-dom/umd/react-dom.development.js"></script>
    <script src="node_modules/alloyeditor/dist/alloy-editor/alloy-editor-no-react.js"></script>
    <script>
        (function () {
            const editor = AlloyEditor.editable('alloy-editor');
        })();
    </script>
</body>
</html>
```

Installed ReactJS and AlloyEditor using yarn: 
```
yarn add react react-dom alloyeditor --save
```

**Comment by andrerom** [comment] 2017-12-21 10:11
@jbalsas Is the issue above known / expected?

**Comment by Drapegnik** [comment] 2018-01-03 16:24
include such fixes work for me:
```js
import React from 'react';
import PropTypes from 'prop-types';
import createClass from 'create-react-class';

// TODO: Remove this file after alloyeditor start to support react@16

// Provide deprecated react globals
React.PropTypes = PropTypes;
React.createClass = createClass;
```

**Comment by josemontiel** [comment] 2018-01-08 17:25
Crash still happening for` react@16.2.0`.

<img width="1029" alt="screen shot 2018-01-08 at 12 24 03 pm" src="https://user-images.githubusercontent.com/7999856/34683044-e3e0f062-f46e-11e7-935e-43b51e7bcb3a.png">

**Comment by biw-ashby** [comment] 2018-01-10 17:54
Same issue here:

<img width="405" alt="screen shot 2018-01-10 at 11 53 49 am" src="https://user-images.githubusercontent.com/23038067/34787476-ff3550e4-f5fc-11e7-82d6-62f85a401def.png">

**Comment by biw-ashby** [comment] 2018-01-10 18:51
I am unable to get alloyeditor `1.5.0` or `1.5.1` to work with either react `16.0.0` or `16.2.0`.
