### ISSUE TITLE
Deleting all content in the editor leads to several errors

### ISSUE THREAD

**Issue by Kirich11** [liferay/alloy-editor#563] opened 2016-07-01 14:54 UTC
So, if you delete all the content in the editor by Ctrl+A, Delete the further editing is unavaliable. Here is a printscreen from your live demo, the same errors occur in my editor where i have alloy-editor-no-react-.js
![wdawd](https://cloud.githubusercontent.com/assets/18256217/16525394/e76b207e-3fb4-11e6-8a34-8d9f7a3903a6.png)

**Comment by ipeychev** [comment] 2016-07-01 15:40
Hello,

We will need more information how to reproduce it. I tried on the live demo and it works fine - please check the attached screencast:
![bug](https://cloud.githubusercontent.com/assets/78014/16526728/dcb949fa-3fb2-11e6-8ebe-1a6595c2b44c.gif)

**Comment by Kirich11** [comment] 2016-07-01 16:51
The errors appear when i hit Enter. I assume that other buttons don't work i.e. you can't type text
![rmihpdbbts](https://cloud.githubusercontent.com/assets/18256217/16528348/21c3142e-3fc5-11e6-8035-a4348828e9ad.gif)

**Comment by Kirich11** [comment] 2016-07-07 08:23
So, this is weird, but i've changed the css for several reasons and the errors disappeared.
I had a container without any `display,` and the editor with `display: table`. I.ve changed the container's `display` to `table` and the editor's to `inline-block`. And it did fix my problem. Don't how css could be possibly related to undefined properpties.

**Comment by ipeychev** [comment] 2016-07-08 06:39
That makes sense, because I tried to reproduce it on the internal [demo](https://github.com/liferay/alloy-editor/blob/f28eac75c3118b1ff53a886135acfe2d0735f979/src/ui/react/demo/index.html) page (not on the live demo) and I couldn't.
If you could provide a simple HTML page with exact steps, we can dig further, otherwise I will close the issue and the resolution will be the solution you provided.

Thanks,

**Comment by Kirich11** [comment] 2016-07-08 06:47
I'll try to provide today/tomorrow an example, but have you noticed the issue on the live demo though
though?

**Comment by Kirich11** [comment] 2016-07-08 07:56
I've made a simple example and it works fine, still the demo has the issue. Try this steps in the live demo to see the errors (if you haven't done it yet):

1. Select all content
2. Delete it.
3. Click somewhere else on the page
4. Try to write something in the editor
5. Click Enter (this is where the errors occur)

As for me, I've solved the issue for myself. 
Thanks

**Comment by ipeychev** [comment] 2016-07-08 18:37
Hello,

Yes, I can reproduce it on our live demo page now. Will try to find the root cause during the weekend.

Thanks,

**Comment by ipeychev** [comment] 2016-07-10 08:20
The issue on the site was in Chrome only and was fixed when border-top and border-bottom got 1px height too.

Thanks again for reporting the issue!

**Closed by ipeychev** 2016-07-10 08:20 UTC
Labels: help wanted, question
