### ISSUE TITLE
Uncaught (in promise) TypeError ... causes React application to bug

### ISSUE THREAD

**Issue by Tzaphkiel** [liferay/alloy-editor#569] opened 2016-07-19 14:49 UTC
When `AlloyEditor `is included inside a React component (`RichEditor`) and this RE is unmounted after some selection and manipulations have been done, the `.destroy()` is called which clears selections...
There is an uncaught error that is thrown because of an object already undefined.

![image](https://cloud.githubusercontent.com/assets/644489/16954266/8c840732-4dd0-11e6-8dc9-f5b59f94e07d.png)

![image](https://cloud.githubusercontent.com/assets/644489/16954208/4564dd0e-4dd0-11e6-8988-94899a0438e4.png)

I basically have a hierarchy of items, selecting one node of them shows the editors or not. So switching from a node with content to a node without content, provided I have made selections in the one with content, triggers the error on Editor destroy.

**Comment by ipeychev** [comment] 2016-07-19 15:34
Hello,

Could you please provide some code, which reproduces the error? There is no way for us to guess what is going on otherwise.
As a hint, "nativeEditor.document" should be the document of the page, where CKEditor was rendered. If it is undefined... probably something killed it before the selection to be removed, but this cannot be determined for sure without reproducible code.

Thanks,

**Comment by Tzaphkiel** [comment] 2016-07-19 21:12
That's going to be tough and might take a bit of time... 
I'll give it a try and check what you mean by the document of the page being killed...

**Comment by ipeychev** [comment] 2016-07-27 01:37
Closing the issue, since without reproducible code we can't do more.

Thanks,

**Closed by ipeychev** 2016-07-27 01:37 UTC
Labels: help wanted, question
