### ISSUE TITLE
How to use CKEditor Plugins in some fields?

### ISSUE THREAD

**Issue by Qlipoth** [liferay/alloy-editor#467] opened 2016-02-17 08:54 UTC
Hello ! i have page with some alloy-editor fields. I want to use Font Size and Family plugin in  these fields:

```
var Selections = [{
        name: 'link',
        buttons: ['linkEdit'],
        test: AlloyEditor.SelectionTest.link
    }, {
        name: 'image',
        buttons: ['imageLeft', 'imageRight'],
        test: AlloyEditor.SelectionTest.image
    }, {
        name: 'text',
        buttons: ['ul', 'h1', 'styles', 'bold', 'italic', 'underline', 'link', 'twitter'],
        test: AlloyEditor.SelectionTest.text
    }, {
        name: 'table',
        buttons: ['tableRow', 'tableColumn', 'tableCell', 'tableRemove'],
        getArrowBoxClasses: AlloyEditor.SelectionGetArrowBoxClasses.table,
        setPosition: AlloyEditor.SelectionSetPosition.table,
        test: AlloyEditor.SelectionTest.table
    }];


    var toolbars = {
        add: {
            buttons: ['image', 'camera', 'hline', 'table'],
            tabIndex: 2
        },
        styles: {
            selections: Selections,
            tabIndex: 1
        }
    };
AlloyEditor.Selections[2].buttons = ['Font', 'FontSize'].concat(AlloyEditor.Selections[2].buttons);
    var editor = AlloyEditor.editable('content', {
        extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value + ',ae_richcombobridge,font'
    });
    var description = AlloyEditor.editable('description',{extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value + ',ae_richcombobridge,font'
    }});
```

When i change font style in description field i have error `'Uncaught IndexSizeError: Failed to execute 'extend' on 'Selection': 1 is larger than the given node's length.'` At the same time it moves the focus to content field

In content field i can change font style. What's the matter?

**Comment by ipeychev** [comment] 2016-02-17 20:54
@jbalsas Could you please take a look on this, Chema?

**Comment by jbalsas** [comment] 2016-02-18 08:22
I'll take a look at this today

**Comment by ipeychev** [comment] 2016-04-30 20:48
Hey @jbalsas,

This issue somehow wasn't resolved. Could you fulfill your promise please and answer the question? Even if @Qlipoth does not need the answer anymore, it might be still helpful for someone else.

Thanks,

**Comment by jbalsas** [comment] 2016-05-03 09:26
Yes, sorry about that, been swamped with a bunch of other stuff... will take a look as soon as possible and document the answer here

**Comment by jbalsas** [comment] 2016-05-11 08:33
Hey @Qlipoth, @ipeychev, after carefully looking into this, this is what we think:

- The issue is the same as https://github.com/liferay/alloy-editor/issues/515. We are about to send a PR with the fix for it, so you'll be able to 
- We haven't been able to reproduce the console error (going back in time a lot). I'm positive we've seen in the past and it didn't actually affect how the editor behaved. Not so long ago we fixed some issues with the editor focus that may have fixed that (#450, #466). We'll keep an eye open in case it comes back.

Hope it clarifies things!

**Comment by jbalsas** [comment] 2016-05-13 08:41
Closing as #515 has been fixed.

@Qlipoth, please reopen if you can still reproduce or there's something else we missed.

Thanks!

**Closed by jbalsas** 2016-05-13 08:41 UTC
Labels: help wanted, question

**Comment by Qlipoth** [comment] 2016-05-13 19:47
Hey @jbalsas, Thanks for the answer!   In the near future i will test it in my project
