### ISSUE TITLE
Bug: when a link is selected and its linkView is openned, pressing on "X" button must remove the link

### ISSUE THREAD

**Issue by ambrinchaudhary** [liferay/alloy-editor#77] opened 2014-12-23 17:24 UTC

**Comment by ipeychev** [comment] 2015-01-20 06:07
This is UX issue - this button actually by design is returning to the styles view and this is exactly what happens. However, the icon "X" is misleading - the user thinks clicking on this button should remove the link.
Closing as invalid, will open UX issue.

**Closed by ipeychev** 2015-01-20 06:07 UTC
