### ISSUE TITLE
Text styling isn't removed when text is deleted

### ISSUE THREAD

**Issue by SpencerWoo** [liferay/alloy-editor#870] opened 2018-08-01 20:58 UTC
## Prelude
When deleting text, the styling remains such that the text that moves up to replace the deleted text takes on that styling.

## Reproduce
1. Go to demo at https://alloyeditor.com/
2. Highlight "In live demo, click/touch here C"
(highlight the header and the first character of the next line)
3. Delete

Actual Behavior : The text is deleted but the style remains and affects other text.

This styling inheritance is correct when some text with that style remains, but when deleting _all_ the text, the styling should not remain and should not affect other text.

## Acceptance Criteria
 - When all text that is styled with StyleA is deleted, StyleA should not exist anymore / influence text.
 - Google Docs behavior

## Notes
I can reproduce with Chrome, IE11.
I cannot reproduce with Firefox.

**Comment by jbalsas** [comment] 2018-08-02 07:35
Hey @SpencerWoo, thanks for reporting!

Unfortunately, this is an issue coming from CKEditor, so we'd need to report it upstream. You can verify the same happens in https://ckeditor.com/ckeditor-4/ and also https://ckeditor.com/ckeditor-5/

What's happening is that on deletion, the tags get merged and the content from the `<p>` tag end up inside the `<h1>` tag. 

I've filed https://github.com/ckeditor/ckeditor-dev/issues/2279 to see what they say about this.

Thanks!

**Closed by jbalsas** 2018-08-02 07:35 UTC

**Comment by duracell80** [comment] 2018-08-02 11:44
Hey Chema, I originally found and reported this. We're out of luck on this one CK have said it's a bug with browsers and will not be fixed. As it's not a bug in their eyes ... it's a feature request. Welcome to my world. It's crazy this is not a feature request.

"Changing this behaviour would be more likely some feature request."
