### ISSUE TITLE
rails integration

### ISSUE THREAD

**Issue by edmemo** [liferay/alloy-editor#377] opened 2015-11-16 17:19 UTC
Hi guys,
congratulations, alloy-editor looks really great. However, integrating it with rails is not (at least for me) an easy task, especially with the asset pipeline.
I'll have to use "vanilla" ckeditor for the moment, and will be happy to use alloy-editor (it really brings a nice interface) when it has a gem or a sample rails project at least. Many thanks.

**Comment by ipeychev** [comment] 2015-11-16 19:01
Hey @edmemo,

AlloyEditor has the same setup as the "vanilla" CKEditor. If you are able to manage to setup CKEditor, it should be easy to setup AlloyEditor too.
We are not familiar with rails and we cannot create a sample project, neither gem.
What exactly are the problems you are facing?

Thanks,

**Comment by ipeychev** [comment] 2015-12-06 21:42
I will close this issue, it is unknown what exactly the problems are. We are not familiar with rails, so we can't create a sample project, but we would happily accept one.

**Closed by ipeychev** 2015-12-06 21:42 UTC
Labels: help wanted

**Comment by rhulse** [comment] 2015-12-19 20:53
@ipeychev I am integrating alloy-editor into a Rails project, and I'd be willing to provide documentation on how to do this. Integrating it turned out to be quite simple when using just your packaged JS.

However, I already have CKEditor in my project and could not get it to behave correctly. For some reason when I use the existing CKE all I get is the standard CKE inline toolbar and not the AlloyEditor behaviours. 

I did a few tests and it is definitely the AlloyEditor.editable that is loading CKE onto the <div>.

Any suggestions on where to start looking?

**Comment by jbalsas** [comment] 2015-12-20 01:38
Hey @rhulse, I assume you're then loading our `*-no-ckeditor` version with your own CKEditor, is that right? If so, which version of CKEditor is present in your system? Can you verify that the default configuration (`extraPlugins`,  `removePlugins`) is being loaded correctly?

Could you provide us a working example or instructions to get it up and running so we could investigate further?

**Comment by rhulse** [comment] 2015-12-20 02:42
Yep, the ```*-no-ckeditor``` versions is in use. I have CKE version 4.5.3 which is loaded first.

Because I want to transition from the old native CKE to AlloyEditor I was using my old config, and just updating a couple of the CMS edit pages to see how it goes. 

It works using my CKE but with the CKE config in the AlloyEditor package.

With my config there seems to be two problems.

First:

```config.extraPlugins = 'mediaembed';```

This plugin stops AlloyEditor attaching to the target div. When I comment it out, it works fine.

Specifying a default toolbar (for the bits of the apps using the native interface):

```config.toolbar = 'Simple';```

causes the native CKE to show, and when you select some text, the Alloy one shows as well.

The first is probably a bug, the second I suspect is not, but merely a configuration aberration.

**Comment by jbalsas** [comment] 2015-12-20 12:18
Hey @rhulse, I've tried the `mediaembed` and `autoembed` plugins before without any issues, so the issue is probably somewhere else.

Could you share the whole config you're passing to the `AlloyEditor.editable` call? I think the problem's probably going to be somewhere around there. You'll probably need to add all the default `ae-*` core plugins that make AlloyEditor work.
