### ISSUE TITLE
Cannot read property 'scrollIntoView' of undefined

### ISSUE THREAD

**Issue by Norm-** [liferay/alloy-editor#358] opened 2015-10-14 18:21 UTC
Hello,

This seems to be a problem with CKEditor and it made its way into alloyeditor.

Problem was mentioned [here](http://ckeditor.com/forums/Support/scrollIntoView-throwing-undefined) and a solution proposed but it received no replies.

Here is how to reproduce it;

* Create a blank editable and initiate editor.
* Make the **first** item you create in the editable an image or a table.
* Apparently, since there is no element present, there is nothing to scrollIntoview. Table prompt (select rows & columns) doesn't show up. Image input shows up but throws the error in the title after trying to insert.

I think a check needs to be added to see if it is the first element. Skip the scrolling if there is nothing in the editable, yet.

p.s. I solved this problem by initiating the editable with a transparent <hr> at the top.

**Comment by ipeychev** [comment] 2015-10-16 04:29
Hey @Norm-,

Here we cannot do much, when the issue is the engine we do one of the following:
1. Report this as a bug and try to work with CKEditor's engineers to fix it.
2. Search and apply a workaround, as you did.

I would suggest you to open a bug report and propose this solution - "_I think a check needs to be added to see if it is the first element. Skip the scrolling if there is nothing in the editable, yet._". They usually respond.

I will close this issue, because it is not strictly related to what we do, but to the engine. I hope you will open a bug to CKEditor and you can add the link as a comment here, so we will follow it and look for a solution too.

Thanks,

**Closed by ipeychev** 2015-10-16 04:29 UTC
